### ISSUE TITLE
Cisco files

### ISSUE THREAD

**Issue by yuvalg72** [yuriskinfo/Visio-stencils-collection#1]
Hey, I have Cisco visio files that maybe could help you to improve this great GitHub project. I will sent it here soon.

**Comment by yuriskinfo** [comment]
Thanks for the reminder, indeed no collection can be complete without Cisco - added new folder Cisco with Routers & Switches, later will upload the rest as well [Cisco](https://github.com/yuriskinfo/Visio-stencils-collection/tree/main/Cisco)

**Comment by yuriskinfo** [comment]
Created new folder "Cisco"
